### ISSUE TITLE
How to submit tact file? 

### ISSUE THREAD

**Issue by westside** [bhaptics/tact-python#1]
```
I would like to play the complete version of "Electric1.tact" file extracted from "designer.bhaptics.com" through Python, just like "Play Effect" on Haptic Designer WebApp. 
I am trying to use the python plug-in here below: https://github.com/bhaptics/tact-python/blob/master/sample.py 
Is it possible to know what "variables" are needed to be sent over websocket? 
(I also tried uploading "Bowshooting.tact" back to bHaptic Designer, but it seems the file old and not accepted?) 

Thank you very much for the support in advance! 

```

**Comment by westside** [comment]
Can you give me more description of your problem?

**Comment by Code4Dopamine** [comment]
Thank you for the response! 

I'm not sure if the following code from sample.py plays the "BowShoot.tact" file effect?

=========================
```
player.register("BowShoot", "BowShoot.tact")

sleep(0.1)
player.submit_registered("BowShoot")
sleep(2)
```

As I think it's only playing from the code here:
```
interval = 0.5
durationMillis = 100

for i in range(20):
    print(i, "back")
    player.submit_dot("backFrame", "VestBack", [{"index": i, "intensity": 100}], durationMillis)
    sleep(interval)

    print(i, "front")
    player.submit_dot("frontFrame", "VestFront", [{"index": i, "intensity": 100}], durationMillis)
    sleep(interval)
```


I want to know the inner-works of how the .tact file (which I assume is a type of .json file submitted to the Haptic Player to trigger the vibrations?)

(For example, I want to play  "Piercing1.tact" file exported from "bHaptic Designer" on the web in python.
Is it possible for it to read all the variables and submit it to the bHaptic Player to the Tactot(Bodysuit)?)



> {"project":{"createdAt":1593684408448,"description":"","layout":{"layouts":{"VestBack":[{"index":0,"x":0,"y":0},{"index":1,"x":0.333,"y":0},{"index":2,"x":0.667,"y":0},{"index":3,"x":1,"y":0},{"index":4,"x":0,"y":0.25},{"index":5,"x":0.333,"y":0.25},{"index":6,"x":0.667,"y":0.25},{"index":7,"x":1,"y":0.25},{"index":8,"x":0,"y":0.5},{"index":9,"x":0.333,"y":0.5},{"index":10,"x":0.667,"y":0.5},{"index":11,"x":1,"y":0.5},{"index":12,"x":0,"y":0.75},{"index":13,"x":0.333,"y":0.75},{"index":14,"x":0.667,"y":0.75},{"index":15,"x":1,"y":0.75},{"index":16,"x":0,"y":1},{"index":17,"x":0.333,"y":1},{"index":18,"x":0.667,"y":1},{"index":19,"x":1,"y":1}],"VestFront":[{"index":0,"x":0,"y":0},{"index":1,"x":0.333,"y":0},{"index":2,"x":0.667,"y":0},{"index":3,"x":1,"y":0},{"index":4,"x":0,"y":0.25},{"index":5,"x":0.333,"y":0.25},{"index":6,"x":0.667,"y":0.25},{"index":7,"x":1,"y":0.25},{"index":8,"x":0,"y":0.5},{"index":9,"x":0.333,"y":0.5},{"index":10,"x":0.667,"y":0.5},{"index":11,"x":1,"y":0.5},{"index":12,"x":0,"y":0.75},{"index":13,"x":0.333,"y":0.75},{"index":14,"x":0.667,"y":0.75},{"index":15,"x":1,"y":0.75},{"index":16,"x":0,"y":1},{"index":17,"x":0.333,"y":1},{"index":18,"x":0.667,"y":1},{"index":19,"x":1,"y":1}]},"name":"Tactot","type":"Tactot"},"mediaFileDuration":0.75,"name":"Piercing1","tracks":[{"effects":[{"modes":{"VestBack":{"dotMode":{"dotConnected":false,"feedback":[{"endTime":300,"playbackType":"NONE","startTime":0,"pointList":[]}]},"mode":"PATH_MODE","pathMode":{"feedback":[{"movingPattern":"CONST_SPEED","playbackType":"FADE_IN_OUT","pointList":[{"intensity":1,"time":0,"x":0.495,"y":0.504}],"visible":true}]}},"VestFront":{"dotMode":{"dotConnected":false,"feedback":[{"endTime":300,"playbackType":"NONE","startTime":0,"pointList":[]}]},"mode":"PATH_MODE","pathMode":{"feedback":[{"movingPattern":"CONST_SPEED","playbackType":"FADE_IN_OUT","pointList":[{"intensity":1,"time":0,"x":0.497,"y":0.504}],"visible":true}]}}},"name":"path","offsetTime":300,"startTime":319},{"modes":{"VestBack":{"dotMode":{"dotConnected":false,"feedback":[{"endTime":300,"playbackType":"NONE","startTime":0,"pointList":[]}]},"mode":"PATH_MODE","pathMode":{"feedback":[]}},"VestFront":{"dotMode":{"dotConnected":false,"feedback":[{"endTime":300,"playbackType":"NONE","startTime":0,"pointList":[]}]},"mode":"PATH_MODE","pathMode":{"feedback":[{"movingPattern":"CONST_SPEED","playbackType":"FADE_OUT","pointList":[{"intensity":1,"time":0,"x":0.498,"y":0.503}],"visible":true}]}}},"name":"path","offsetTime":300,"startTime":0}],"enable":true},{"enable":true,"effects":[]}],"updatedAt":1593684408448,"id":"-MBDzZqJCMiHxwLn7YnC"},"durationMillis":0,"intervalMillis":20,"size":20}

[Piercing1.zip](https://github.com/bhaptics/tact-python/files/5542352/Piercing1.zip)

**Comment by westside** [comment]
Really sorry for the late response. 
Examples are quite outdated and I'll update the examples and let you know.
Sorry again!

**Comment by westside** [comment]
* There was a bug on submiting feeback.

https://github.com/bhaptics/tact-python/commit/608ad7c1708cf0a38cfba071a47325320d58ae30
![image](https://user-images.githubusercontent.com/1837913/99503782-f6bde880-29c1-11eb-9176-17d6a6244faf.png)





* I fixed the issue and please pull the latest master.
